version: "3.7"

networks:
  shared:
    name: local.mattbot.com

volumes:
  gems: {}
  mysql-data: {}
  sockets: {}

x-base: &base
  build:
    context: .
    target: build
  stdin_open: true
  tty: true
  links:
    - db
  # env_file:
  #   - docker/app.env
  volumes:
    - "./:/rails"
    - gems:/usr/local/bundle
    - sockets:/rails/tmp/sockets
  environment:
    APPLICATION_VERSION: ${APPLICATION_VERSION}
    MYSQL_HOST: db
    MYSQL_PORT: 3306
    MYSQL_USER: root
    MYSQL_PASSWORD: ""
  tmpfs:
    - /rails/public/assets
  networks:
    shared: {}

services:
  app:
    <<: *base
    depends_on:
      - db
    ports:
      - 3000:3000
    tmpfs:
      - /tmp

  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 33062:3306
    volumes:
      - mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: y
    networks:
      shared: {}