version: "3.7"

networks:
  shared:
    name: local.mattbot.com

volumes:
  gems: {}
  mysql-data: {}
  sockets: {}

x-base: &base
  build:
    context: .
    target: build
  stdin_open: true
  tty: true
  links:
    - db
  # env_file:
  #   - docker/app.env
  volumes:
    - "./:/app"
    - gems:/usr/local/bundle
    - sockets:/app/tmp/sockets
  environment:
    APPLICATION_VERSION: ${APPLICATION_VERSION}
    MYSQL_HOST: db
    MYSQL_PORT: 3306
    MYSQL_USER: root
    MYSQL_PASSWORD: ""
  tmpfs:
    - /app/public/assets
  networks:
    shared: {}

services:
  app:
    <<: *base
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - nginx
    tmpfs:
      - /tmp
    # command: ["/bin/bash", "-c", "script/start_puma_development.sh", "rails"]

  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      # - 33060:3306
      - 33062:3306
    volumes:
      - mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: y
    networks:
      shared: {}

  nginx:
    image: nginx:stable-alpine
    volumes:
      # - ./docker/nginx/conf.d:/etc/nginx/conf.d
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - sockets:/tmp/sockets
      # Replace with real SSL certificate:
      # - "./ssl:/etc/nginx/certs"
      # - ${HOME}/.ssl:/etc/nginx/certs
    ports:
      - "443:443"
    networks:
      shared: {}
    tmpfs:
      - /data/nginx/cache
    command: /bin/sh -c "exec nginx -g 'daemon off;'"