FROM ruby:3.4.6-alpine3.22 AS bundle

RUN apk update \
  && apk add -Uuv \
  alpine-sdk \
  bash \
  build-base \
  curl \
  gcompat \
  git \
  groff \
  less \
  libc6-compat \
  # libssl1.1 \
  libxml2-dev \
  libxslt-dev \
  linux-headers \
  mariadb-dev \
  mysql \
  nodejs \
  npm \
  openssl \
  openssl-dev \
  postgresql-dev \
  readline-dev \
  sqlite-dev \
  sudo \
  tzdata \
  vips-dev \
  xz \
  yaml-dev \
  yarn \
  zlib-dev \
  && rm -rf /var/cache/apk/*

RUN update-ca-certificates

ARG USER=rails
ENV RAILS_USER=$USER

ARG UID=1000
ENV RAILS_UID=$UID

ARG GID=1000
ENV RAILS_GID=$GID

RUN adduser -D $RAILS_USER -u $RAILS_UID -g $RAILS_GID \
  && echo "$RAILS_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$RAILS_USER \
  && chmod 0440 /etc/sudoers.d/$RAILS_USER

# ADD --chown=$RAILS_UID:$RAILS_GID https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem \
#  /aurora/rds-combined-ca-bundle.pem

COPY --chown=$RAILS_USER . /app/

WORKDIR /app/

RUN gem update --system
RUN gem install bundler --version 2.7.2

COPY --chown=$RAILS_USER Gemfile Gemfile.lock /app/

RUN DEBUG_RESOLVER=1 BUNDLE_IGNORE_MESSAGES=true bundle install --jobs $(getconf _NPROCESSORS_ONLN)

FROM bundle as build

# RUN bundle-audit update

# Provide *default* values for some of our configuration variables:
ENV \
  CI=false \
  DEV_MODE=false \
  LOG_LEVEL=info \
  RAILS_CACHING=false \
  RAILS_FORCE_SSL=false \
  RAILS_LOG_TO_STDOUT=true \
  RAILS_SERVE_STATIC_FILES=true \
  PATH=/app/bin:$PATH

# COPY --chown=$RAILS_USER ./app/ /app/app
# COPY --chown=$RAILS_USER ./bin/ /app/bin
# COPY --chown=$RAILS_USER ./config/ /app/config
# COPY --chown=$RAILS_USER ./lib/ /app/lib
# COPY --chown=$RAILS_USER ./vendor/ /app/vendor
# COPY --chown=$RAILS_USER Rakefile /app/

RUN mkdir -p /app/tmp/sockets
RUN chown -R $RAILS_USER:$RAILS_USER /app/tmp
RUN chown -R $RAILS_USER:$RAILS_USER /app/tmp/sockets

ENTRYPOINT ["/app/docker/entrypoint.sh"]

EXPOSE 3000

ARG application_version
ENV APPLICATION_VERSION=$application_version

STOPSIGNAL SIGINT

FROM build as deploy
